### ISSUE TITLE
addMemeberRole not working

### ISSUE THREAD

**Issue by ruNovel** [marcocusano/discord-php#1]
Hello!
The add role function does not work.
But the function to remove roles works well!
I do like this
$discord->guilds->memberRole("Guild ID", "my ID", "783273854646222868")
or
$discord->guilds->addMemberRole("Guild ID", "my ID", "783273854646222868")

I gave permission to the bot.

**Comment by marcocusano** [comment]
Hello there, sorry for the delay.

The Discord PHP [v1](/marcocusano/discord-php/tree/v1) is officially deprecated. I've pushed a [v2](/marcocusano/discord-php/tree/v2).
If you are still interested, you can check it out!

To perform the same action on the v2, you've to do something like:
```PHP
// Get the GuildMember Object
$member = New \Discord\Client\Members($discordClient, "GUILD_ID", "MEMBER_ID");
// Add a Role
$member->addRole("ROLE_ID");
```
