### ISSUE TITLE
$discord->guilds->members(...) does not work

### ISSUE THREAD

**Issue by Yoobe** [marcocusano/discord-php#2]
Hi,

When I want to use this function I have this error : 

`
PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'Discord\Helpers\Collection' does not have a method 'members' in ...\discord-php\vendor\team-reflex\discord-php\src\Discord\Repository\AbstractRepository.php on line 405
`

What can be the root cause ?

Thanks.

**Comment by marcocusano** [comment]
Hello there, sorry for the delay.

The Discord PHP [v1](/marcocusano/discord-php/tree/v1) is officially deprecated. I've pushed a [v2](/marcocusano/discord-php/tree/v2).
If you are interested, you can check it out!
